name: deep-storm
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - scikit-image
  - scikit-learn
  - tqdm
  - h5py
  - scipy
  - numpy
  - pytorch=1.8.0
  - torchvison

# This file will need to be modified depending on the version of pytorch that your machine supports.
